{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-reflector.clusterRoleName" . }}
  labels:
    {{- include "cluster-reflector.labels" . | nindent 4 }}
  {{- with include "cluster-reflector.annotations" . }}
  {{- if . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-reflector.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-reflector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
