{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-reflector.clusterRoleName" . }}
  labels:
    {{- include "cluster-reflector.labels" . | nindent 4 }}
  {{- with include "cluster-reflector.annotations" . }}
  {{- if . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  {{- end }}
rules:
# Core API - nodes
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
{{- if .Values.appDiscovery.enabled }}
{{- if .Values.appDiscovery.fallbackWorkloads }}
# Apps API - workloads for fallback discovery
- apiGroups: ["apps"]
  resources:
    {{- range .Values.appDiscovery.workloadKinds }}
    {{- if eq . "Deployment" }}
    - "deployments"
    {{- else if eq . "StatefulSet" }}
    - "statefulsets"
    {{- else if eq . "DaemonSet" }}
    - "daemonsets"
    {{- else if eq . "ReplicaSet" }}
    - "replicasets"
    {{- end }}
    {{- end }}
  verbs: ["get", "list", "watch"]
{{- end }}
{{- if .Values.appDiscovery.preferCRD }}
# Custom Resource - AppVersions
- apiGroups: ["cluster.grid.sce.com"]
  resources: ["appversions"]
  verbs: ["get", "list", "watch"]
{{- end }}
{{- end }}
{{- end }}
