apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-reflector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-reflector.labels" . | nindent 4 }}
  {{- with include "cluster-reflector.annotations" . }}
  {{- if . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cluster-reflector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluster-reflector.selectorLabels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cluster-reflector.serviceAccountName" . }}
      {{- with include "cluster-reflector.podSecurityContext" . }}
      {{- if . }}
      securityContext:
        {{- . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "cluster-reflector.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- include "cluster-reflector.args" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with include "cluster-reflector.resources" . }}
          {{- if . }}
          resources:
            {{- . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with include "cluster-reflector.securityContext" . }}
          {{- if . }}
          securityContext:
            {{- . | nindent 12 }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with include "cluster-reflector.nodeSelector" . }}
      {{- if . }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with include "cluster-reflector.tolerations" . }}
      {{- if . }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with include "cluster-reflector.affinity" . }}
      {{- if . }}
      affinity:
        {{- . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with include "cluster-reflector.topologySpreadConstraints" . }}
      {{- if . }}
      topologySpreadConstraints:
        {{- . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.runtimeClassName }}
      runtimeClassName: {{ . }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- if .Values.hostPID }}
      hostPID: true
      {{- end }}
      {{- if .Values.hostIPC }}
      hostIPC: true
      {{- end }}
      {{- if .Values.shareProcessNamespace }}
      shareProcessNamespace: true
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
