{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cluster-reflector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-reflector.labels" . | nindent 4 }}
  {{- with include "cluster-reflector.annotations" . }}
  {{- if . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "cluster-reflector.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from specified namespaces
    {{- if .Values.networkPolicy.allowedNamespaces }}
    {{- range .Values.networkPolicy.allowedNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ . }}
      ports:
        - protocol: TCP
          port: 8080
    {{- end }}
    {{- else }}
    # Allow ingress from any namespace by default
    - ports:
        - protocol: TCP
          port: 8080
    {{- end }}
    {{- with .Values.networkPolicy.additionalIngressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
    {{- if .Values.networkPolicy.allowKubeAPI }}
    # Allow egress to Kubernetes API server
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    {{- end }}
    {{- with .Values.networkPolicy.additionalEgressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
